#pragma once

#include <algorithm>
#include <array>
#include <string_view>

namespace adaptive_algorithm::runners::detail
{
    enum class RunnerOptionId
    {
        config_file,
        example_name,
        dimension,
        rho,
        max_outer_iterations,
        max_inner_iterations,
        doerfler_theta_x,
        doerfler_theta_y,
        uniform_x_refinement,
        uniform_y_refinement,
        force_accept_inner_with_effective_rho,
        compute_g_estimator,
        compute_g_estimator_on_empty_y_marking_stop,
        compute_g_estimator_every_inner_iteration,
        g_solver,
        g_solver_tolerance,
        g_solver_memory_limit_mb,
        uniform_refinement_mode,
        polynomial_degree,
        zero_tol,
        divergence_residual_l2_tolerance,
        eta_squared_stop,
        inner_estimator_squared_stop,
        max_wall_time_seconds,
        max_y_true_dofs,
        max_x_true_dofs,
        max_dofs_target,
        memory_limit_mb,
        memory_reserve_mb,
        memory_guard_safety_factor,
        memory_guard_near_cap_fraction,
        increased_accuracy,
        main_solver,
        main_solver_pardiso_memory_mode,
        main_solver_max_iterations,
        main_solver_tolerance,
        main_solver_symmetry_tolerance,
        main_solver_direct_residual_retry,
        main_solver_direct_residual_retry_tolerance,
        main_solver_diagnostics,
        main_solver_memory_limit_mb,
        main_solver_ooc_auto_switch,
        main_solver_ooc_switch_threshold,
        main_solver_ooc_switch_to_lu,
        main_solver_reuse_symbolic_analysis,
        output_directory,
        quiet,
        list_examples,
        show_help,
        check_divergence_residual,
        stop_on_empty_y_marking,
        local_time_slab_closure,
        use_adaptive_initial_guess,
        solve_main_system_correction,
        fused_error_and_flux_diagnostics,
        local_error_reuse_patch_solve_workspace,
        deterministic_estimator_reductions,
        doerfler_near_tie_tolerance,
        refinement_edge_query_cache,
        refinement_batch_target_split_cells,
        post_flush_closure_mode,
        post_flush_affected_containment_only,
        refinement_full_conformity_check,
        refinement_main_closure_query_mode,
        local_error_patch_tile_size,
        local_error_cell_chunk_size,
        local_error_max_threads,
        local_error_memory_budget_mb,
        local_error_worker_context_mode,
        local_error_context_storage,
        local_error_state_index_mode,
        local_error_cell_state_cache_mode,
        local_error_cell_state_cache_budget_mb,
        local_error_cell_state_representation,
        local_error_flux_diagnostics_mode,
        local_error_patch_solver,
        local_error_coefficient_fast_path,
        local_error_compact_state_shadow,
        shared_context_validation,
        slab_reconstruction_operator_mode,
        main_assembly_max_threads,
        slab_reconstruction_max_threads,
        main_assembly_memory_budget_mb,
        slab_reconstruction_memory_budget_mb,
        main_two_pass_numeric_fill_max_threads,
        main_two_pass_numeric_fill_memory_budget_mb,
        time_slab_backend,
        allow_copied_time_slab_estimator_fallback,
        virtual_backend_diagnostics,
        solver_diagnostics_enabled,
        solver_diagnostics_export_matrix_market,
        solver_diagnostics_export_rhs,
        solver_diagnostics_export_solution,
        solver_diagnostics_max_export_dofs,
        output_profile,
        save_heavy_diagnostics,
        export_history,
        save_estimator_components,
        save_refinement_history,
        save_mesh_statistics,
        save_iteration_snapshots,
        save_snapshot_dofs,
        enable_timing_breakdown,
        timing_history_filename,
        timing_detail_level
    };

    enum class RunnerOptionValueType
    {
        string_value,
        int_value,
        double_value,
        bool_value,
        bool_flag
    };

    struct CliOptionSpec
    {
        std::string_view flag{};
        std::string_view value_name{};
        std::string_view description{};
        std::string_view continuation{};
        RunnerOptionId id = RunnerOptionId::show_help;
        RunnerOptionValueType value_type = RunnerOptionValueType::bool_flag;
        bool bool_flag_value = false;
        bool visible_in_usage = true;
    };

    struct ConfigOptionSpec
    {
        std::string_view key{};
        RunnerOptionId id = RunnerOptionId::show_help;
        RunnerOptionValueType value_type = RunnerOptionValueType::string_value;
        bool invert_bool = false;
        bool visible_in_usage = true;
    };

    inline constexpr auto cli_option_specs = std::to_array<CliOptionSpec>({
        {"--config", "PATH", "Load parameters from a flat .yml config file.",
         {}, RunnerOptionId::config_file, RunnerOptionValueType::string_value, false},
        {"--example", "NAME", "Predefined example name.",
         {}, RunnerOptionId::example_name, RunnerOptionValueType::string_value, false},
        {"--dimension", "N", "Expected spatial dimension of the selected example.",
         "Supported: 1, 2. If omitted, the dimension is inferred from the registered example.",
         RunnerOptionId::dimension, RunnerOptionValueType::int_value, false},
        {"--dim-space", "N", "Alias for --dimension.",
         {}, RunnerOptionId::dimension, RunnerOptionValueType::int_value, false},
        {"--rho", "VALUE", "Rho parameter for the inner Y loop.",
         {}, RunnerOptionId::rho, RunnerOptionValueType::double_value, false},
        {"--max-outer", "N", "Maximum number of outer X iterations.",
         {}, RunnerOptionId::max_outer_iterations, RunnerOptionValueType::int_value, false},
        {"--max-inner", "N", "Maximum number of inner Y iterations.",
         {}, RunnerOptionId::max_inner_iterations, RunnerOptionValueType::int_value, false},
        {"--force-accept-inner-with-effective-rho", {},
         "Accept the last inner iteration at max-inner by computing the required effective rho.",
         "Configured rho is ignored as an inner stopping criterion while this mode is active.",
         RunnerOptionId::force_accept_inner_with_effective_rho, RunnerOptionValueType::bool_flag, true},
        {"--no-force-accept-inner-with-effective-rho", {},
         "Use the configured rho criterion for normal inner-loop acceptance.",
         {}, RunnerOptionId::force_accept_inner_with_effective_rho, RunnerOptionValueType::bool_flag, false},
        {"--effective-rho-only-inner-acceptance", {},
         "Alias for --force-accept-inner-with-effective-rho.",
         {}, RunnerOptionId::force_accept_inner_with_effective_rho, RunnerOptionValueType::bool_flag, true},
        {"--compute-g-estimator", {},
         "Assemble and solve the accepted-iteration G^delta enriched reconstruction.",
         "G^delta uses Q_{p+1,p+1} on the accepted Y mesh by default.",
         RunnerOptionId::compute_g_estimator, RunnerOptionValueType::bool_flag, true},
        {"--no-compute-g-estimator", {},
         "Do not construct or solve the G^delta enriched reconstruction.",
         {}, RunnerOptionId::compute_g_estimator, RunnerOptionValueType::bool_flag, false},
        {"--compute-g-estimator-on-empty-y-marking-stop", {},
         "Also compute G^delta when stop_on_empty_y_marking ends the inner loop.",
         "Default: disabled. Rejected Y iterations compute G^delta only with --compute-g-estimator-every-inner-iteration.",
         RunnerOptionId::compute_g_estimator_on_empty_y_marking_stop, RunnerOptionValueType::bool_flag, true},
        {"--no-compute-g-estimator-on-empty-y-marking-stop", {},
         "Do not compute G^delta for an empty-Y-marking stop.",
         {}, RunnerOptionId::compute_g_estimator_on_empty_y_marking_stop, RunnerOptionValueType::bool_flag, false},
        {"--compute-g-estimator-every-inner-iteration", {},
         "Compute and save G^delta diagnostics for every inner Y iteration.",
         "Requires --compute-g-estimator and can be much more expensive than accepted-only G^delta.",
         RunnerOptionId::compute_g_estimator_every_inner_iteration, RunnerOptionValueType::bool_flag, true},
        {"--no-compute-g-estimator-every-inner-iteration", {},
         "Compute G^delta only for accepted inner iterations.",
         {}, RunnerOptionId::compute_g_estimator_every_inner_iteration, RunnerOptionValueType::bool_flag, false},
        {"--g-solver", "NAME",
         "Solver used for accepted-iteration G^delta reconstruction solves.",
         "Default: same_as_main. Supported: same_as_main plus the main-solver choices.",
         RunnerOptionId::g_solver, RunnerOptionValueType::string_value, false},
        {"--g-solver-tolerance", "VALUE",
         "Tolerance for the G^delta reconstruction solver.",
         "Default: 0, meaning inherit the effective main-solver tolerance.",
         RunnerOptionId::g_solver_tolerance, RunnerOptionValueType::double_value, false},
        {"--g-solver-memory-limit-mb", "MB",
         "Direct-solver memory limit for the G^delta reconstruction solver.",
         "Default: 0, meaning inherit the effective main-solver memory limit.",
         RunnerOptionId::g_solver_memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"--theta-x", "VALUE", "Dorfler bulk parameter for X marking.",
         {}, RunnerOptionId::doerfler_theta_x, RunnerOptionValueType::double_value, false},
        {"--theta-y", "VALUE", "Dorfler bulk parameter for Y marking.",
         {}, RunnerOptionId::doerfler_theta_y, RunnerOptionValueType::double_value, false},
        {"--uniform-x-refinement", {},
         "Refine every active X^delta cell after each accepted outer solve instead of Dörfler-marking X.",
         "Useful for uniform-refinement convergence checks. The inner Y loop remains adaptive.",
         RunnerOptionId::uniform_x_refinement, RunnerOptionValueType::bool_flag, true},
        {"--adaptive-x-refinement", {},
         "Use the default Dörfler X-marking instead of uniform X refinement.",
         {}, RunnerOptionId::uniform_x_refinement, RunnerOptionValueType::bool_flag, false},
        {"--uniform-y-refinement", {},
         "Refine every active Y^delta cell after a non-accepted inner solve instead of Dörfler-marking Y.",
         "Useful for uniform-refinement rate comparisons.",
         RunnerOptionId::uniform_y_refinement, RunnerOptionValueType::bool_flag, true},
        {"--adaptive-y-refinement", {},
         "Use the default Dörfler Y-marking instead of uniform Y refinement.",
         {}, RunnerOptionId::uniform_y_refinement, RunnerOptionValueType::bool_flag, false},
        {"--uniform-refinement-mode", "MODE",
         "Set the effective refinement mode.",
         "Supported: adaptive, uniform_x, uniform_y, uniform_xy. Explicit --uniform-x-refinement or --uniform-y-refinement flags override this mode.",
         RunnerOptionId::uniform_refinement_mode, RunnerOptionValueType::string_value, false},
        {"--p", "N", "Polynomial degree. Supported: 1, 2, 3, 4.",
         {}, RunnerOptionId::polynomial_degree, RunnerOptionValueType::int_value, false},
        {"--zero-tol", "VALUE", "Zero tolerance used in assembly and filtering.",
         {}, RunnerOptionId::zero_tol, RunnerOptionValueType::double_value, false},
        {"--divergence-tol", "VALUE", "Allowed L2 norm for the divergence-residual sanity check.",
         {}, RunnerOptionId::divergence_residual_l2_tolerance, RunnerOptionValueType::double_value, false},
        {"--eta-stop", "VALUE", "Stop once eta_squared is below this threshold.",
         {}, RunnerOptionId::eta_squared_stop, RunnerOptionValueType::double_value, false},
        {"--inner-estimator-stop", "VALUE",
         "Stop the inner loop once the estimator squared is below this threshold.",
         {}, RunnerOptionId::inner_estimator_squared_stop, RunnerOptionValueType::double_value, false},
        {"--max-wall-time-seconds", "VALUE",
         "Soft wall-time budget for the adaptive run.",
         "Default: 0 disables. The active solve is not interrupted; the driver stops before the next adaptive iteration.",
         RunnerOptionId::max_wall_time_seconds, RunnerOptionValueType::double_value, false},
        {"--max-y-dofs", "N",
         "Stop before the next inner solve if Y^delta true DoFs exceed this limit.",
         "Default: 500000. Use 0 to disable.",
         RunnerOptionId::max_y_true_dofs, RunnerOptionValueType::int_value, false},
        {"--max-x-dofs", "N",
         "Stop before the next outer iteration if X^delta true DoFs exceed this limit.",
         "Default: 0 disables. Production configs use this as the primary DoF target.",
         RunnerOptionId::max_x_true_dofs, RunnerOptionValueType::int_value, false},
        {"--max-dofs-target", "TARGET",
         "Select which DoF cap is the primary requested maximum.",
         "Supported: y, x. Existing configs default to y; Snellius production configs set x.",
         RunnerOptionId::max_dofs_target, RunnerOptionValueType::string_value, false},
        {"--memory-limit-mb", "MB",
         "Whole-process adaptive-run memory cap.",
         "Default: inherits --main-solver-memory-limit-mb. Use 0 together with --main-solver-memory-limit-mb 0 to disable.",
         RunnerOptionId::memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"--memory-reserve-mb", "MB",
         "Minimum Linux MemAvailable reserve kept by the adaptive memory guard.",
         "Default: 2048 MiB.",
         RunnerOptionId::memory_reserve_mb, RunnerOptionValueType::double_value, false},
        {"--memory-guard-safety-factor", "VALUE",
         "Multiplier applied to adaptive and PARDISO memory estimates.",
         "Default: 1.15.",
         RunnerOptionId::memory_guard_safety_factor, RunnerOptionValueType::double_value, false},
        {"--memory-guard-near-cap-fraction", "VALUE",
         "Fraction of the memory cap at which thread counts are reduced and PARDISO out-of-core switching is enabled earlier.",
         "Default: 0.85.",
         RunnerOptionId::memory_guard_near_cap_fraction, RunnerOptionValueType::double_value, false},
        {"--increased-accuracy", {},
         "Use higher runner accuracy: QSpace += 2, QTime += 2, and solver residual tolerances are tightened by a factor 10.",
         {}, RunnerOptionId::increased_accuracy, RunnerOptionValueType::bool_flag, true},
        {"--high-accuracy", {},
         "Alias for --increased-accuracy.",
         {}, RunnerOptionId::increased_accuracy, RunnerOptionValueType::bool_flag, true},
        {"--normal-accuracy", {},
         "Disable the increased-accuracy quadrature and solver-tolerance boost.",
         {}, RunnerOptionId::increased_accuracy, RunnerOptionValueType::bool_flag, false},
        {"--main-solver", "NAME",
         "Main-system solver choice.",
         "Default: pardiso_ldlt in MKL builds, sparse_lu otherwise. Supported: sparse_lu, pardiso_lu, pardiso_ldlt, pardiso_ldlt_auto, minres_parabolic_graph_norm. Without MKL, PARDISO choices fall back to sparse_lu.",
         RunnerOptionId::main_solver, RunnerOptionValueType::string_value, false},
        {"--main-solver-pardiso-memory-mode", "MODE",
         "MKL PARDISO memory mode for the main solver.",
         "Supported: in_core, auto, out_of_core. Used only with PARDISO solvers.",
         RunnerOptionId::main_solver_pardiso_memory_mode, RunnerOptionValueType::string_value, false},
        {"--main-solver-max-iterations", "N",
         "Maximum number of iterations for the main-system iterative solver.",
         "Ignored by direct solvers.",
         RunnerOptionId::main_solver_max_iterations, RunnerOptionValueType::int_value, false},
        {"--main-solver-tolerance", "VALUE",
         "Relative tolerance for the main-system iterative solver.",
         "Ignored by direct solvers.",
         RunnerOptionId::main_solver_tolerance, RunnerOptionValueType::double_value, false},
        {"--main-solver-symmetry-tolerance", "VALUE",
         "Relative symmetry tolerance for pardiso_ldlt_auto.",
         "Used only when selecting between PardisoLDLT and PardisoLU automatically.",
         RunnerOptionId::main_solver_symmetry_tolerance, RunnerOptionValueType::double_value, false},
        {"--main-solver-direct-residual-retry", {},
         "Enable direct-solver true-residual validation and retry with a safer direct solver.",
         "Default: enabled in MKL PARDISO builds, disabled otherwise. PARDISO LDLT retries with PARDISO LU; unavailable PARDISO requests use SparseLU in non-MKL builds.",
         RunnerOptionId::main_solver_direct_residual_retry, RunnerOptionValueType::bool_flag, true},
        {"--no-main-solver-direct-residual-retry", {},
         "Disable direct-solver residual retry.",
         {}, RunnerOptionId::main_solver_direct_residual_retry, RunnerOptionValueType::bool_flag, false},
        {"--main-solver-direct-residual-retry-tolerance", "VALUE",
         "True relative residual threshold for direct-solver retry.",
         "Default: 1e-10. Used only when direct residual retry is enabled.",
         RunnerOptionId::main_solver_direct_residual_retry_tolerance, RunnerOptionValueType::double_value, false},
        {"--main-solver-diagnostics", "MODE",
         "Post-solve main-system diagnostic mode.",
         "Supported: off, summary, detailed. Summary records true residuals; detailed also performs the full matrix symmetry diagnostic.",
         RunnerOptionId::main_solver_diagnostics, RunnerOptionValueType::string_value, false},
        {"--main-solver-memory-limit-mb", "MB",
         "Direct main-solver memory limit.",
         "Default: 10000 MiB. Use 0 to disable.",
         RunnerOptionId::main_solver_memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"--main-solver-ooc-auto-switch", {},
         "Switch MKL PARDISO from in-core to out-of-core before factorization when the memory estimate approaches the limit.",
         "Default: disabled. PARDISO out-of-core is an explicit memory-pressure experiment.",
         RunnerOptionId::main_solver_ooc_auto_switch, RunnerOptionValueType::bool_flag, true},
        {"--no-main-solver-ooc-auto-switch", {},
         "Disable automatic PARDISO out-of-core fallback.",
         {}, RunnerOptionId::main_solver_ooc_auto_switch, RunnerOptionValueType::bool_flag, false},
        {"--main-solver-ooc-switch-threshold", "VALUE",
         "Fraction of --main-solver-memory-limit-mb at which in-core PARDISO switches to out-of-core.",
         "Default: 0.85.",
         RunnerOptionId::main_solver_ooc_switch_threshold, RunnerOptionValueType::double_value, false},
        {"--main-solver-ooc-switch-to-lu", {},
         "Use PARDISO LU for automatic out-of-core fallback from LDLT.",
         "Default: enabled because LDLT out-of-core has shown weaker residuals on the saddle system.",
         RunnerOptionId::main_solver_ooc_switch_to_lu, RunnerOptionValueType::bool_flag, true},
        {"--main-solver-ooc-keep-ldlt", {},
         "Keep PARDISO LDLT when automatic out-of-core fallback is triggered.",
         {}, RunnerOptionId::main_solver_ooc_switch_to_lu, RunnerOptionValueType::bool_flag, false},
        {"--main-solver-reuse-symbolic-analysis", {},
         "Reuse SparseLU symbolic analysis when the same solver sees an identical sparsity pattern.",
         "Default: enabled. Numeric factorization is still recomputed every solve.",
         RunnerOptionId::main_solver_reuse_symbolic_analysis, RunnerOptionValueType::bool_flag, true},
        {"--no-main-solver-reuse-symbolic-analysis", {},
         "Disable SparseLU symbolic-analysis reuse.",
         {}, RunnerOptionId::main_solver_reuse_symbolic_analysis, RunnerOptionValueType::bool_flag, false},
        {"--output", "PATH", "Output directory. Defaults to algorithm_data/<example>/.",
         {}, RunnerOptionId::output_directory, RunnerOptionValueType::string_value, false},
        {"--print-iterations", {}, "Enable iteration-table printing.",
         {}, RunnerOptionId::quiet, RunnerOptionValueType::bool_flag, false},
        {"--quiet", {}, "Disable iteration-table printing.",
         {}, RunnerOptionId::quiet, RunnerOptionValueType::bool_flag, true},
        {"--check-divergence", {}, "Enforce the divergence-residual sanity check.",
         {}, RunnerOptionId::check_divergence_residual, RunnerOptionValueType::bool_flag, true},
        {"--no-check-divergence", {}, "Disable the divergence-residual sanity check.",
         {}, RunnerOptionId::check_divergence_residual, RunnerOptionValueType::bool_flag, false},
        {"--stop-on-empty-y-marking", {},
         "Stop if Y-marking becomes empty before the threshold is met.",
         {}, RunnerOptionId::stop_on_empty_y_marking, RunnerOptionValueType::bool_flag, true},
        {"--allow-empty-y-marking", {},
         "Continue even if Y-marking becomes empty.",
         {}, RunnerOptionId::stop_on_empty_y_marking, RunnerOptionValueType::bool_flag, false},
        {"--local-time-slab-closure", {},
         "Temporally close marked Y cells crossed by existing time interfaces.",
         "Only marked split cells are closed; non-split marked cells use the normal refinement rule. Default: disabled.",
         RunnerOptionId::local_time_slab_closure, RunnerOptionValueType::bool_flag, true},
        {"--no-local-time-slab-closure", {},
         "Disable local time-slab closure for marked Y cells.",
         {}, RunnerOptionId::local_time_slab_closure, RunnerOptionValueType::bool_flag, false},
        {"--use-adaptive-initial-guess", {},
         "Use the previous adaptive solution prolongated to the refined space as the main-solve initial guess.",
         {}, RunnerOptionId::use_adaptive_initial_guess, RunnerOptionValueType::bool_flag, true},
        {"--no-adaptive-initial-guess", {},
         "Do not pass a prolongated adaptive initial guess to the main solve.",
         {}, RunnerOptionId::use_adaptive_initial_guess, RunnerOptionValueType::bool_flag, false},
        {"--solve-main-system-correction", {},
         "Solve K e = b - K x0 and set x = x0 + e when an adaptive initial guess is available.",
         {}, RunnerOptionId::solve_main_system_correction, RunnerOptionValueType::bool_flag, true},
        {"--no-solve-main-system-correction", {},
         "Pass the adaptive initial guess directly instead of solving the correction equation.",
         {}, RunnerOptionId::solve_main_system_correction, RunnerOptionValueType::bool_flag, false},
        {"--fused-error-and-flux-diagnostics", {},
         "Use fused 2+1D local-error/flux-diagnostic data when the reconstruction path provides it.",
         "Default: enabled. Use --no-fused-error-and-flux-diagnostics to force the standalone diagnostic fallback.",
         RunnerOptionId::fused_error_and_flux_diagnostics, RunnerOptionValueType::bool_flag, true},
        {"--no-fused-error-and-flux-diagnostics", {},
         "Disable fused local-error/flux diagnostics and use the standalone diagnostic fallback.",
         {}, RunnerOptionId::fused_error_and_flux_diagnostics, RunnerOptionValueType::bool_flag, false},
        {"--local-error-reuse-patch-solve-workspace", {},
         "Reuse per-thread dense local patch solve workspaces in 2+1D local-error solves.",
         "Default: enabled. Use --no-local-error-reuse-patch-solve-workspace to force the legacy allocation-heavy patch solve path.",
         RunnerOptionId::local_error_reuse_patch_solve_workspace, RunnerOptionValueType::bool_flag, true},
        {"--no-local-error-reuse-patch-solve-workspace", {},
         "Disable per-thread dense local patch solve workspace reuse in 2+1D local-error solves.",
         {}, RunnerOptionId::local_error_reuse_patch_solve_workspace, RunnerOptionValueType::bool_flag, false},
        {"--deterministic-estimator-reductions", {},
         "Use deterministic source-cell estimator reductions and Dörfler marking.",
         "Default: enabled. Use --no-deterministic-estimator-reductions for legacy debug comparisons.",
         RunnerOptionId::deterministic_estimator_reductions, RunnerOptionValueType::bool_flag, true},
        {"--no-deterministic-estimator-reductions", {},
         "Use the legacy unordered-map estimator reduction path.",
         {}, RunnerOptionId::deterministic_estimator_reductions, RunnerOptionValueType::bool_flag, false},
        {"--doerfler-near-tie-tolerance", "VALUE",
         "Diagnostic tolerance for counting near ties at the Dörfler cutoff.",
         "Default: 0.0. This records near ties but never changes marking.",
         RunnerOptionId::doerfler_near_tie_tolerance, RunnerOptionValueType::double_value, false},
        {"--refinement-edge-query-cache", {},
         "Enable the per-refinement-call 2D edge-query cache.",
         "Default: enabled. The cache is cleared whenever the active edge index is updated.",
         RunnerOptionId::refinement_edge_query_cache, RunnerOptionValueType::bool_flag, true},
        {"--no-refinement-edge-query-cache", {},
         "Disable the per-refinement-call 2D edge-query cache.",
         {}, RunnerOptionId::refinement_edge_query_cache, RunnerOptionValueType::bool_flag, false},
        {"--refinement-batch-target-split-cells", "N",
         "Target number of split active cells before flushing a 2D indexed-refinement batch.",
         "Default: 32. Dependency closure and queue-empty flushes still happen immediately when required.",
         RunnerOptionId::refinement_batch_target_split_cells, RunnerOptionValueType::int_value, false},
        {"--post-flush-closure-mode", "MODE",
         "Choose the 2D post-flush forced-closure query set.",
         "Supported: off_debug, split_edges_only_debug, split_and_inherited_edges, affected_edges, presplit_neighbour, all_faces_debug. Default: presplit_neighbour.",
         RunnerOptionId::post_flush_closure_mode, RunnerOptionValueType::string_value, false},
        {"--post-flush-affected-containment-only", {},
         "Use the experimental containment-only query path for affected-edge post-flush closure.",
         "Default: disabled. The full exact/ancestor/containment overlap path remains the production default.",
         RunnerOptionId::post_flush_affected_containment_only, RunnerOptionValueType::bool_flag, true},
        {"--no-post-flush-affected-containment-only", {},
         "Disable the experimental affected-edge containment-only post-flush query path.",
         {}, RunnerOptionId::post_flush_affected_containment_only, RunnerOptionValueType::bool_flag, false},
        {"--refinement-full-conformity-check", {},
         "Run the full 2D active spatial conformity verifier after every refinement, even in release builds.",
         "Default: disabled. Intended for post-flush closure experiments.",
         RunnerOptionId::refinement_full_conformity_check, RunnerOptionValueType::bool_flag, true},
        {"--no-refinement-full-conformity-check", {},
         "Disable the full 2D active spatial conformity verifier in release builds.",
         {}, RunnerOptionId::refinement_full_conformity_check, RunnerOptionValueType::bool_flag, false},
        {"--refinement-main-closure-query-mode", "MODE",
         "Choose the 2D main-queue closure edge-query mode.",
         "Supported: exact_and_ancestor, exact_ancestor_plus_containment, old_bidirectional_debug. Default: exact_and_ancestor.",
         RunnerOptionId::refinement_main_closure_query_mode, RunnerOptionValueType::string_value, false},
        {"--local-error-patch-tile-size", "N",
         "Use tiled 2+1D local-error patch assembly/solves with at most N patches per tile. 0 uses the degree-aware default.",
         {}, RunnerOptionId::local_error_patch_tile_size, RunnerOptionValueType::int_value, false},
        {"--local-error-cell-chunk-size", "N",
         "When tiled 2+1D local-error assembly is active, stream shared cell-state caches in chunks of at most N slab cells. 0 uses the degree-aware default.",
         {}, RunnerOptionId::local_error_cell_chunk_size, RunnerOptionValueType::int_value, false},
        {"--local-error-max-threads", "N",
         "Maximum OpenMP threads for 2+1D local-error work. 0 uses the automatic cap.",
         {}, RunnerOptionId::local_error_max_threads, RunnerOptionValueType::int_value, false},
        {"--local-error-memory-budget-mb", "MB",
         "Approximate memory budget for 2+1D local-error thread selection. 0 disables budget limiting.",
         {}, RunnerOptionId::local_error_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"--local-error-worker-context-mode", "MODE",
         "Deprecated debug alias for local-error context storage.",
         "Supported: persistent, per_chunk_debug, persistent_all_p_debug. If used without --local-error-context-storage, it maps to the matching debug storage mode.",
         RunnerOptionId::local_error_worker_context_mode, RunnerOptionValueType::string_value, false},
        {"--local-error-context-storage", "MODE",
         "Choose the local-error context storage/shadow mode.",
         "Supported: shared_immutable, per_chunk_debug, persistent_per_thread_debug, shared_immutable_shadow. Default: shared_immutable. Shadow mode builds the shared immutable context but keeps current computation.",
         RunnerOptionId::local_error_context_storage, RunnerOptionValueType::string_value, false},
        {"--local-error-state-index-mode", "MODE",
         "Choose the 2+1D local-error slab-cell state lookup mode.",
         "Supported: flat, map_debug. Default: flat.",
         RunnerOptionId::local_error_state_index_mode, RunnerOptionValueType::string_value, false},
        {"--local-error-cell-state-cache-mode", "MODE",
         "Choose the 2+1D cross-tile local-error cell-state cache mode.",
         "Supported: off, tile, bounded_lru, lifetime_window, full_if_fits. Default: off.",
         RunnerOptionId::local_error_cell_state_cache_mode, RunnerOptionValueType::string_value, false},
        {"--local-error-cell-state-cache-budget-mb", "MB",
         "Memory budget for bounded_lru/full_if_fits local-error cell-state reuse. 0 disables bounded storage.",
         {}, RunnerOptionId::local_error_cell_state_cache_budget_mb, RunnerOptionValueType::double_value, false},
        {"--local-error-cell-state-representation", "MODE",
         "Choose the 2+1D local-error cell-state representation.",
         "Supported: compact_split, monolithic_debug. Default: compact_split.",
         RunnerOptionId::local_error_cell_state_representation, RunnerOptionValueType::string_value, false},
        {"--local-error-flux-diagnostics-mode", "MODE",
         "Choose the 2+1D flux-diagnostics execution mode.",
         "Supported: auto, streaming_reuse, standalone. Default: auto.",
         RunnerOptionId::local_error_flux_diagnostics_mode, RunnerOptionValueType::string_value, false},
        {"--local-error-patch-solver", "MODE",
         "Choose the 2+1D dense local patch solver.",
         "Supported: current_dense, reduced_scalar_dense, auto. Default: current_dense.",
         RunnerOptionId::local_error_patch_solver, RunnerOptionValueType::string_value, false},
        {"--local-error-coefficient-fast-path", {},
         "Use coefficient-aware local-error fast paths for identity/constant diffusion and zero load.",
         "Default: enabled. Use --no-local-error-coefficient-fast-path for generic coefficient debug comparisons.",
         RunnerOptionId::local_error_coefficient_fast_path, RunnerOptionValueType::bool_flag, true},
        {"--no-local-error-coefficient-fast-path", {},
         "Disable coefficient-aware local-error fast paths and force the generic q-point coefficient path.",
         {}, RunnerOptionId::local_error_coefficient_fast_path, RunnerOptionValueType::bool_flag, false},
        {"--local-error-compact-state-shadow", {},
         "Build compact/split local-error shadow states on sampled cells and compare against monolithic CellData.",
         "Default: disabled. This is a debug validation mode and does not change the production computation path.",
         RunnerOptionId::local_error_compact_state_shadow, RunnerOptionValueType::bool_flag, true},
        {"--no-local-error-compact-state-shadow", {},
         "Disable compact/split local-error shadow-state validation.",
         {}, RunnerOptionId::local_error_compact_state_shadow, RunnerOptionValueType::bool_flag, false},
        {"--shared-context-validation", "MODE",
         "Choose shared immutable context validation sampling.",
         "Supported: off, sample, full_debug. Default: off. Shadow context storage validates by default.",
         RunnerOptionId::shared_context_validation, RunnerOptionValueType::string_value, false},
        {"--slab-reconstruction-operator-mode", "MODE",
         "Choose coefficient handling for copied-slab reconstruction assembly.",
         "Supported: auto, identity_zero_load_fast_path, constant_diffusion_fast_path, generic_variable_path. Default: auto.",
         RunnerOptionId::slab_reconstruction_operator_mode, RunnerOptionValueType::string_value, false},
        {"--main-assembly-max-threads", "N",
         "Maximum OpenMP threads for main-system assembly. Default 4; 0 uses the automatic OpenMP maximum.",
         {}, RunnerOptionId::main_assembly_max_threads, RunnerOptionValueType::int_value, false},
        {"--slab-reconstruction-max-threads", "N",
         "Maximum OpenMP threads for 2+1D slab reconstruction assembly/solves. Default 4; 0 uses the automatic OpenMP maximum.",
         {}, RunnerOptionId::slab_reconstruction_max_threads, RunnerOptionValueType::int_value, false},
        {"--main-assembly-memory-budget-mb", "MB",
         "Recorded memory budget for main-system assembly thread-local buffers. 0 disables budget accounting.",
         {}, RunnerOptionId::main_assembly_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"--slab-reconstruction-memory-budget-mb", "MB",
         "Approximate memory budget for 2+1D slab reconstruction thread-local caches. 0 disables budget limiting.",
         {}, RunnerOptionId::slab_reconstruction_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"--main-two-pass-numeric-fill-max-threads", "N",
         "Maximum OpenMP threads for memory-bounded two-pass main-system numeric fill. 0 uses the default of 4.",
         {}, RunnerOptionId::main_two_pass_numeric_fill_max_threads, RunnerOptionValueType::int_value, false},
        {"--main-two-pass-numeric-fill-memory-budget-mb", "MB",
         "Approximate memory budget for two-pass numeric-fill thread-local buffers. 0 disables budget limiting.",
         {}, RunnerOptionId::main_two_pass_numeric_fill_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"--time-slab-backend", "NAME",
         "Time-slab backend interface to construct. Supported: copied_mesh.",
         "Default: copied_mesh.",
         RunnerOptionId::time_slab_backend, RunnerOptionValueType::string_value, false},
        {"--allow-copied-time-slab-estimator-fallback", {},
         "Compatibility flag accepted by older configs; copied_mesh is always used.",
         "This flag has no effect in the published backend set.",
         RunnerOptionId::allow_copied_time_slab_estimator_fallback, RunnerOptionValueType::bool_flag, true},
        {"--strict-virtual-time-slab-estimator", {},
         "Compatibility flag accepted by older configs; copied_mesh is always used.",
         "This flag has no effect in the published backend set.",
         RunnerOptionId::allow_copied_time_slab_estimator_fallback, RunnerOptionValueType::bool_flag, false},
        {"--virtual-backend-diagnostics", {},
         "Compatibility flag accepted by older configs; virtual diagnostics are disabled.",
         "This flag has no effect in the published backend set.",
         RunnerOptionId::virtual_backend_diagnostics, RunnerOptionValueType::bool_flag, true},
        {"--no-virtual-backend-diagnostics", {},
         "Compatibility flag accepted by older configs; virtual diagnostics are disabled.",
         {},
         RunnerOptionId::virtual_backend_diagnostics, RunnerOptionValueType::bool_flag, false},
        {"--solver-diagnostics", {},
         "Write per-main-solve solver diagnostics metadata files.",
         "Matrix/RHS/solution export stays disabled unless requested separately.",
         RunnerOptionId::solver_diagnostics_enabled, RunnerOptionValueType::bool_flag, true},
        {"--no-solver-diagnostics", {},
         "Disable per-main-solve solver diagnostics metadata files.",
         {}, RunnerOptionId::solver_diagnostics_enabled, RunnerOptionValueType::bool_flag, false},
        {"--export-main-matrix-market", {},
         "When solver diagnostics are enabled, export the full main-system matrix in MatrixMarket format if below the DoF cap.",
         {}, RunnerOptionId::solver_diagnostics_export_matrix_market, RunnerOptionValueType::bool_flag, true},
        {"--export-main-rhs", {},
         "When solver diagnostics are enabled, export the full main-system RHS vector if below the DoF cap.",
         {}, RunnerOptionId::solver_diagnostics_export_rhs, RunnerOptionValueType::bool_flag, true},
        {"--export-main-solution", {},
         "When solver diagnostics are enabled, export the solved full main-system vector if below the DoF cap.",
         {}, RunnerOptionId::solver_diagnostics_export_solution, RunnerOptionValueType::bool_flag, true},
        {"--solver-diagnostics-max-export-dofs", "N",
         "Maximum main-system rows for MatrixMarket/RHS/solution export.",
         "Default: 20000.",
         RunnerOptionId::solver_diagnostics_max_export_dofs, RunnerOptionValueType::int_value, false},
        {"--output-profile", "NAME",
         "Grouped output policy.",
         "Supported: minimal, production, benchmark, debug. Individual output flags still override the profile.",
         RunnerOptionId::output_profile, RunnerOptionValueType::string_value, false},
        {"--save-heavy-diagnostics", {},
         "Enable detailed estimator components, refinement history, snapshots, and detailed timing.",
         "Snapshot DoF binaries remain opt-in via --save-snapshot-dofs.",
         RunnerOptionId::save_heavy_diagnostics, RunnerOptionValueType::bool_flag, true},
        {"--export", {}, "Enable CSV/text history export.",
         {}, RunnerOptionId::export_history, RunnerOptionValueType::bool_flag, true},
        {"--no-export", {}, "Disable CSV/text history export.",
         {}, RunnerOptionId::export_history, RunnerOptionValueType::bool_flag, false},
        {"--estimator-components", {}, "Enable detailed estimator-component output.",
         {}, RunnerOptionId::save_estimator_components, RunnerOptionValueType::bool_flag, true},
        {"--no-estimator-components", {}, "Skip detailed estimator-component output.",
         {}, RunnerOptionId::save_estimator_components, RunnerOptionValueType::bool_flag, false},
        {"--refinement-history", {}, "Enable refinement_history.txt export.",
         {}, RunnerOptionId::save_refinement_history, RunnerOptionValueType::bool_flag, true},
        {"--no-refinement-history", {}, "Skip refinement_history.txt.",
         {}, RunnerOptionId::save_refinement_history, RunnerOptionValueType::bool_flag, false},
        {"--mesh-statistics", {}, "Enable final mesh-statistics lines in the summary.",
         {}, RunnerOptionId::save_mesh_statistics, RunnerOptionValueType::bool_flag, true},
        {"--no-mesh-statistics", {}, "Skip mesh-statistics lines in the summary.",
         {}, RunnerOptionId::save_mesh_statistics, RunnerOptionValueType::bool_flag, false},
        {"--no-snapshots", {}, "Disable per-iteration mesh/error snapshots.",
         {}, RunnerOptionId::save_iteration_snapshots, RunnerOptionValueType::bool_flag, false},
        {"--save-snapshots", {}, "Save per-iteration mesh/error snapshots.",
         {}, RunnerOptionId::save_iteration_snapshots, RunnerOptionValueType::bool_flag, true},
        {"--no-snapshot-dofs", {}, "Disable DoF binaries inside the snapshots.",
         {}, RunnerOptionId::save_snapshot_dofs, RunnerOptionValueType::bool_flag, false},
        {"--save-snapshot-dofs", {}, "Also save DoF binaries inside the snapshots.",
         {}, RunnerOptionId::save_snapshot_dofs, RunnerOptionValueType::bool_flag, true},
        {"--enable-timing-breakdown", {}, "Enable timing breakdown collection and CSV export.",
         {}, RunnerOptionId::enable_timing_breakdown, RunnerOptionValueType::bool_flag, true},
        {"--no-timing-breakdown", {}, "Disable timing breakdown collection and CSV export.",
         {}, RunnerOptionId::enable_timing_breakdown, RunnerOptionValueType::bool_flag, false},
        {"--timing-history-filename", "NAME", "Timing breakdown CSV filename.",
         "Default: timing_history.csv.",
         RunnerOptionId::timing_history_filename, RunnerOptionValueType::string_value, false},
        {"--timing-detail-level", "LEVEL", "Timing breakdown detail level.",
         "Supported: summary, detailed. Currently both write run-level aggregate rows.",
         RunnerOptionId::timing_detail_level, RunnerOptionValueType::string_value, false},
        {"--list-examples", {}, "Print the available example names and dimensions and exit.",
         {}, RunnerOptionId::list_examples, RunnerOptionValueType::bool_flag, true},
        {"--help", {}, "Print this help text and exit.",
         {}, RunnerOptionId::show_help, RunnerOptionValueType::bool_flag, true}
    });

    inline constexpr auto config_option_specs = std::to_array<ConfigOptionSpec>({
        {"example", RunnerOptionId::example_name, RunnerOptionValueType::string_value, false},
        {"example_name", RunnerOptionId::example_name, RunnerOptionValueType::string_value, false},
        {"dimension", RunnerOptionId::dimension, RunnerOptionValueType::int_value, false},
        {"dim_space", RunnerOptionId::dimension, RunnerOptionValueType::int_value, false},
        {"spatial_dimension", RunnerOptionId::dimension, RunnerOptionValueType::int_value, false},
        {"rho", RunnerOptionId::rho, RunnerOptionValueType::double_value, false},
        {"max_outer", RunnerOptionId::max_outer_iterations, RunnerOptionValueType::int_value, false},
        {"max_outer_iterations", RunnerOptionId::max_outer_iterations, RunnerOptionValueType::int_value, false},
        {"max_inner", RunnerOptionId::max_inner_iterations, RunnerOptionValueType::int_value, false},
        {"max_inner_iterations", RunnerOptionId::max_inner_iterations, RunnerOptionValueType::int_value, false},
        {"theta_x", RunnerOptionId::doerfler_theta_x, RunnerOptionValueType::double_value, false},
        {"doerfler_theta_x", RunnerOptionId::doerfler_theta_x, RunnerOptionValueType::double_value, false},
        {"theta_y", RunnerOptionId::doerfler_theta_y, RunnerOptionValueType::double_value, false},
        {"doerfler_theta_y", RunnerOptionId::doerfler_theta_y, RunnerOptionValueType::double_value, false},
        {"uniform_x_refinement", RunnerOptionId::uniform_x_refinement, RunnerOptionValueType::bool_value, false},
        {"x_uniform_refinement", RunnerOptionId::uniform_x_refinement, RunnerOptionValueType::bool_value, false},
        {"uniform_y_refinement", RunnerOptionId::uniform_y_refinement, RunnerOptionValueType::bool_value, false},
        {"y_uniform_refinement", RunnerOptionId::uniform_y_refinement, RunnerOptionValueType::bool_value, false},
        {"force_accept_inner_with_effective_rho", RunnerOptionId::force_accept_inner_with_effective_rho, RunnerOptionValueType::bool_value, false},
        {"effective_rho_only_inner_acceptance", RunnerOptionId::force_accept_inner_with_effective_rho, RunnerOptionValueType::bool_value, false},
        {"compute_g_estimator", RunnerOptionId::compute_g_estimator, RunnerOptionValueType::bool_value, false},
        {"compute_g_delta_enriched_estimator", RunnerOptionId::compute_g_estimator, RunnerOptionValueType::bool_value, false},
        {"compute_g_estimator_on_empty_y_marking_stop", RunnerOptionId::compute_g_estimator_on_empty_y_marking_stop, RunnerOptionValueType::bool_value, false},
        {"compute_g_delta_on_empty_y_marking_stop", RunnerOptionId::compute_g_estimator_on_empty_y_marking_stop, RunnerOptionValueType::bool_value, false},
        {"compute_g_estimator_every_inner_iteration", RunnerOptionId::compute_g_estimator_every_inner_iteration, RunnerOptionValueType::bool_value, false},
        {"compute_g_delta_every_inner_iteration", RunnerOptionId::compute_g_estimator_every_inner_iteration, RunnerOptionValueType::bool_value, false},
        {"g_solver", RunnerOptionId::g_solver, RunnerOptionValueType::string_value, false},
        {"g_solver_tolerance", RunnerOptionId::g_solver_tolerance, RunnerOptionValueType::double_value, false},
        {"g_solver_memory_limit_mb", RunnerOptionId::g_solver_memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"uniform_refinement_mode", RunnerOptionId::uniform_refinement_mode, RunnerOptionValueType::string_value, false},
        {"p", RunnerOptionId::polynomial_degree, RunnerOptionValueType::int_value, false},
        {"polynomial_degree", RunnerOptionId::polynomial_degree, RunnerOptionValueType::int_value, false},
        {"zero_tol", RunnerOptionId::zero_tol, RunnerOptionValueType::double_value, false},
        {"divergence_tol", RunnerOptionId::divergence_residual_l2_tolerance, RunnerOptionValueType::double_value, false},
        {"divergence_residual_l2_tolerance", RunnerOptionId::divergence_residual_l2_tolerance, RunnerOptionValueType::double_value, false},
        {"eta_stop", RunnerOptionId::eta_squared_stop, RunnerOptionValueType::double_value, false},
        {"eta_squared_stop", RunnerOptionId::eta_squared_stop, RunnerOptionValueType::double_value, false},
        {"inner_estimator_stop", RunnerOptionId::inner_estimator_squared_stop, RunnerOptionValueType::double_value, false},
        {"inner_estimator_squared_stop", RunnerOptionId::inner_estimator_squared_stop, RunnerOptionValueType::double_value, false},
        {"max_wall_time_seconds", RunnerOptionId::max_wall_time_seconds, RunnerOptionValueType::double_value, false},
        {"wall_time_limit_seconds", RunnerOptionId::max_wall_time_seconds, RunnerOptionValueType::double_value, false},
        {"max_y_dofs", RunnerOptionId::max_y_true_dofs, RunnerOptionValueType::int_value, false},
        {"max_y_true_dofs", RunnerOptionId::max_y_true_dofs, RunnerOptionValueType::int_value, false},
        {"max_x_dofs", RunnerOptionId::max_x_true_dofs, RunnerOptionValueType::int_value, false},
        {"max_x_true_dofs", RunnerOptionId::max_x_true_dofs, RunnerOptionValueType::int_value, false},
        {"max_dofs_target", RunnerOptionId::max_dofs_target, RunnerOptionValueType::string_value, false},
        {"max_dof_target", RunnerOptionId::max_dofs_target, RunnerOptionValueType::string_value, false},
        {"memory_limit_mb", RunnerOptionId::memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"memory_reserve_mb", RunnerOptionId::memory_reserve_mb, RunnerOptionValueType::double_value, false},
        {"memory_guard_safety_factor", RunnerOptionId::memory_guard_safety_factor, RunnerOptionValueType::double_value, false},
        {"memory_guard_near_cap_fraction", RunnerOptionId::memory_guard_near_cap_fraction, RunnerOptionValueType::double_value, false},
        {"increased_accuracy", RunnerOptionId::increased_accuracy, RunnerOptionValueType::bool_value, false},
        {"high_accuracy", RunnerOptionId::increased_accuracy, RunnerOptionValueType::bool_value, false},
        {"main_solver", RunnerOptionId::main_solver, RunnerOptionValueType::string_value, false},
        {"main_solver_pardiso_memory_mode", RunnerOptionId::main_solver_pardiso_memory_mode, RunnerOptionValueType::string_value, false},
        {"main_solver_max_iterations", RunnerOptionId::main_solver_max_iterations, RunnerOptionValueType::int_value, false},
        {"main_solver_tolerance", RunnerOptionId::main_solver_tolerance, RunnerOptionValueType::double_value, false},
        {"main_solver_symmetry_tolerance", RunnerOptionId::main_solver_symmetry_tolerance, RunnerOptionValueType::double_value, false},
        {"main_solver_direct_residual_retry", RunnerOptionId::main_solver_direct_residual_retry, RunnerOptionValueType::bool_value, false},
        {"main_solver_direct_residual_retry_tolerance", RunnerOptionId::main_solver_direct_residual_retry_tolerance, RunnerOptionValueType::double_value, false},
        {"main_solver_diagnostics", RunnerOptionId::main_solver_diagnostics, RunnerOptionValueType::string_value, false},
        {"main_solver.diagnostics", RunnerOptionId::main_solver_diagnostics, RunnerOptionValueType::string_value, false},
        {"main_solver_memory_limit_mb", RunnerOptionId::main_solver_memory_limit_mb, RunnerOptionValueType::double_value, false},
        {"main_solver_ooc_auto_switch", RunnerOptionId::main_solver_ooc_auto_switch, RunnerOptionValueType::bool_value, false},
        {"main_solver_ooc_switch_threshold", RunnerOptionId::main_solver_ooc_switch_threshold, RunnerOptionValueType::double_value, false},
        {"main_solver_ooc_switch_to_lu", RunnerOptionId::main_solver_ooc_switch_to_lu, RunnerOptionValueType::bool_value, false},
        {"main_solver_reuse_symbolic_analysis", RunnerOptionId::main_solver_reuse_symbolic_analysis, RunnerOptionValueType::bool_value, false},
        {"output", RunnerOptionId::output_directory, RunnerOptionValueType::string_value, false},
        {"output_directory", RunnerOptionId::output_directory, RunnerOptionValueType::string_value, false},
        {"quiet", RunnerOptionId::quiet, RunnerOptionValueType::bool_value, false},
        {"print_iterations", RunnerOptionId::quiet, RunnerOptionValueType::bool_value, true},
        {"print_iteration_tables", RunnerOptionId::quiet, RunnerOptionValueType::bool_value, true},
        {"check_divergence", RunnerOptionId::check_divergence_residual, RunnerOptionValueType::bool_value, false},
        {"check_divergence_residual", RunnerOptionId::check_divergence_residual, RunnerOptionValueType::bool_value, false},
        {"stop_on_empty_y_marking", RunnerOptionId::stop_on_empty_y_marking, RunnerOptionValueType::bool_value, false},
        {"empty_y_marking_stops", RunnerOptionId::stop_on_empty_y_marking, RunnerOptionValueType::bool_value, false},
        {"local_time_slab_closure", RunnerOptionId::local_time_slab_closure, RunnerOptionValueType::bool_value, false},
        {"use_adaptive_initial_guess", RunnerOptionId::use_adaptive_initial_guess, RunnerOptionValueType::bool_value, false},
        {"adaptive_initial_guess", RunnerOptionId::use_adaptive_initial_guess, RunnerOptionValueType::bool_value, false},
        {"solve_main_system_correction", RunnerOptionId::solve_main_system_correction, RunnerOptionValueType::bool_value, false},
        {"main_system_correction", RunnerOptionId::solve_main_system_correction, RunnerOptionValueType::bool_value, false},
        {"fused_error_and_flux_diagnostics", RunnerOptionId::fused_error_and_flux_diagnostics, RunnerOptionValueType::bool_value, false},
        {"time_slab.fused_error_and_flux_diagnostics", RunnerOptionId::fused_error_and_flux_diagnostics, RunnerOptionValueType::bool_value, false},
        {"fused_flux_diagnostics", RunnerOptionId::fused_error_and_flux_diagnostics, RunnerOptionValueType::bool_value, false},
        {"local_error_reuse_patch_solve_workspace", RunnerOptionId::local_error_reuse_patch_solve_workspace, RunnerOptionValueType::bool_value, false},
        {"time_slab.local_error_reuse_patch_solve_workspace", RunnerOptionId::local_error_reuse_patch_solve_workspace, RunnerOptionValueType::bool_value, false},
        {"patch_solve_workspace_reuse", RunnerOptionId::local_error_reuse_patch_solve_workspace, RunnerOptionValueType::bool_value, false},
        {"deterministic_estimator_reductions", RunnerOptionId::deterministic_estimator_reductions, RunnerOptionValueType::bool_value, false},
        {"time_slab.deterministic_estimator_reductions", RunnerOptionId::deterministic_estimator_reductions, RunnerOptionValueType::bool_value, false},
        {"doerfler_near_tie_tolerance", RunnerOptionId::doerfler_near_tie_tolerance, RunnerOptionValueType::double_value, false},
        {"doerfler.near_tie_tolerance", RunnerOptionId::doerfler_near_tie_tolerance, RunnerOptionValueType::double_value, false},
        {"refinement_edge_query_cache", RunnerOptionId::refinement_edge_query_cache, RunnerOptionValueType::bool_value, false},
        {"refinement.edge_query_cache", RunnerOptionId::refinement_edge_query_cache, RunnerOptionValueType::bool_value, false},
        {"refinement_batch_target_split_cells", RunnerOptionId::refinement_batch_target_split_cells, RunnerOptionValueType::int_value, false},
        {"refinement.batch_target_split_cells", RunnerOptionId::refinement_batch_target_split_cells, RunnerOptionValueType::int_value, false},
        {"post_flush_closure_mode", RunnerOptionId::post_flush_closure_mode, RunnerOptionValueType::string_value, false},
        {"refinement.post_flush_closure_mode", RunnerOptionId::post_flush_closure_mode, RunnerOptionValueType::string_value, false},
        {"post_flush_affected_containment_only", RunnerOptionId::post_flush_affected_containment_only, RunnerOptionValueType::bool_value, false},
        {"refinement.post_flush_affected_containment_only", RunnerOptionId::post_flush_affected_containment_only, RunnerOptionValueType::bool_value, false},
        {"refinement_full_conformity_check", RunnerOptionId::refinement_full_conformity_check, RunnerOptionValueType::bool_value, false},
        {"refinement.full_conformity_check", RunnerOptionId::refinement_full_conformity_check, RunnerOptionValueType::bool_value, false},
        {"refinement_main_closure_query_mode", RunnerOptionId::refinement_main_closure_query_mode, RunnerOptionValueType::string_value, false},
        {"refinement.main_closure_query_mode", RunnerOptionId::refinement_main_closure_query_mode, RunnerOptionValueType::string_value, false},
        {"local_error_patch_tile_size", RunnerOptionId::local_error_patch_tile_size, RunnerOptionValueType::int_value, false},
        {"patch_tile_size", RunnerOptionId::local_error_patch_tile_size, RunnerOptionValueType::int_value, false},
        {"local_error_cell_chunk_size", RunnerOptionId::local_error_cell_chunk_size, RunnerOptionValueType::int_value, false},
        {"cell_chunk_size", RunnerOptionId::local_error_cell_chunk_size, RunnerOptionValueType::int_value, false},
        {"local_error_max_threads", RunnerOptionId::local_error_max_threads, RunnerOptionValueType::int_value, false},
        {"local_error_memory_budget_mb", RunnerOptionId::local_error_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"local_error_worker_context_mode", RunnerOptionId::local_error_worker_context_mode, RunnerOptionValueType::string_value, false},
        {"local_error.worker_context_mode", RunnerOptionId::local_error_worker_context_mode, RunnerOptionValueType::string_value, false},
        {"local_error_context_storage", RunnerOptionId::local_error_context_storage, RunnerOptionValueType::string_value, false},
        {"local_error.context_storage", RunnerOptionId::local_error_context_storage, RunnerOptionValueType::string_value, false},
        {"local_error_state_index_mode", RunnerOptionId::local_error_state_index_mode, RunnerOptionValueType::string_value, false},
        {"local_error.state_index_mode", RunnerOptionId::local_error_state_index_mode, RunnerOptionValueType::string_value, false},
        {"local_error_cell_state_cache_mode", RunnerOptionId::local_error_cell_state_cache_mode, RunnerOptionValueType::string_value, false},
        {"local_error.cell_state_cache_mode", RunnerOptionId::local_error_cell_state_cache_mode, RunnerOptionValueType::string_value, false},
        {"local_error_cell_state_cache_budget_mb", RunnerOptionId::local_error_cell_state_cache_budget_mb, RunnerOptionValueType::double_value, false},
        {"local_error.cell_state_cache_budget_mb", RunnerOptionId::local_error_cell_state_cache_budget_mb, RunnerOptionValueType::double_value, false},
        {"local_error_cell_state_representation", RunnerOptionId::local_error_cell_state_representation, RunnerOptionValueType::string_value, false},
        {"local_error.cell_state_representation", RunnerOptionId::local_error_cell_state_representation, RunnerOptionValueType::string_value, false},
        {"local_error_flux_diagnostics_mode", RunnerOptionId::local_error_flux_diagnostics_mode, RunnerOptionValueType::string_value, false},
        {"local_error.flux_diagnostics_mode", RunnerOptionId::local_error_flux_diagnostics_mode, RunnerOptionValueType::string_value, false},
        {"local_error_patch_solver", RunnerOptionId::local_error_patch_solver, RunnerOptionValueType::string_value, false},
        {"local_error.patch_solver", RunnerOptionId::local_error_patch_solver, RunnerOptionValueType::string_value, false},
        {"local_error_coefficient_fast_path", RunnerOptionId::local_error_coefficient_fast_path, RunnerOptionValueType::bool_value, false},
        {"local_error.coefficient_fast_path", RunnerOptionId::local_error_coefficient_fast_path, RunnerOptionValueType::bool_value, false},
        {"local_error_compact_state_shadow", RunnerOptionId::local_error_compact_state_shadow, RunnerOptionValueType::bool_value, false},
        {"local_error.compact_state_shadow", RunnerOptionId::local_error_compact_state_shadow, RunnerOptionValueType::bool_value, false},
        {"shared_context_validation", RunnerOptionId::shared_context_validation, RunnerOptionValueType::string_value, false},
        {"shared_context.validation", RunnerOptionId::shared_context_validation, RunnerOptionValueType::string_value, false},
        {"slab_reconstruction_operator_mode", RunnerOptionId::slab_reconstruction_operator_mode, RunnerOptionValueType::string_value, false},
        {"slab_reconstruction.operator_mode", RunnerOptionId::slab_reconstruction_operator_mode, RunnerOptionValueType::string_value, false},
        {"main_assembly_max_threads", RunnerOptionId::main_assembly_max_threads, RunnerOptionValueType::int_value, false},
        {"slab_reconstruction_max_threads", RunnerOptionId::slab_reconstruction_max_threads, RunnerOptionValueType::int_value, false},
        {"main_assembly_memory_budget_mb", RunnerOptionId::main_assembly_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"slab_reconstruction_memory_budget_mb", RunnerOptionId::slab_reconstruction_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"main_two_pass_numeric_fill_max_threads", RunnerOptionId::main_two_pass_numeric_fill_max_threads, RunnerOptionValueType::int_value, false},
        {"main_two_pass_numeric_fill_memory_budget_mb", RunnerOptionId::main_two_pass_numeric_fill_memory_budget_mb, RunnerOptionValueType::double_value, false},
        {"time_slab_backend", RunnerOptionId::time_slab_backend, RunnerOptionValueType::string_value, false},
        {"time_slab_backend_type", RunnerOptionId::time_slab_backend, RunnerOptionValueType::string_value, false},
        {"allow_copied_time_slab_estimator_fallback", RunnerOptionId::allow_copied_time_slab_estimator_fallback, RunnerOptionValueType::bool_value, false},
        {"time_slab.allow_copied_estimator_fallback", RunnerOptionId::allow_copied_time_slab_estimator_fallback, RunnerOptionValueType::bool_value, false},
        {"virtual_backend_diagnostics", RunnerOptionId::virtual_backend_diagnostics, RunnerOptionValueType::bool_value, false},
        {"time_slab.virtual_backend_diagnostics", RunnerOptionId::virtual_backend_diagnostics, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics.enabled", RunnerOptionId::solver_diagnostics_enabled, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics_enabled", RunnerOptionId::solver_diagnostics_enabled, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics.export_matrix_market", RunnerOptionId::solver_diagnostics_export_matrix_market, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics_export_matrix_market", RunnerOptionId::solver_diagnostics_export_matrix_market, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics.export_rhs", RunnerOptionId::solver_diagnostics_export_rhs, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics_export_rhs", RunnerOptionId::solver_diagnostics_export_rhs, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics.export_solution", RunnerOptionId::solver_diagnostics_export_solution, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics_export_solution", RunnerOptionId::solver_diagnostics_export_solution, RunnerOptionValueType::bool_value, false},
        {"solver_diagnostics.max_export_dofs", RunnerOptionId::solver_diagnostics_max_export_dofs, RunnerOptionValueType::int_value, false},
        {"solver_diagnostics_max_export_dofs", RunnerOptionId::solver_diagnostics_max_export_dofs, RunnerOptionValueType::int_value, false},
        {"output_profile", RunnerOptionId::output_profile, RunnerOptionValueType::string_value, false},
        {"save_heavy_diagnostics", RunnerOptionId::save_heavy_diagnostics, RunnerOptionValueType::bool_value, false},
        {"export", RunnerOptionId::export_history, RunnerOptionValueType::bool_value, false},
        {"export_history", RunnerOptionId::export_history, RunnerOptionValueType::bool_value, false},
        {"estimator_components", RunnerOptionId::save_estimator_components, RunnerOptionValueType::bool_value, false},
        {"save_estimator_components", RunnerOptionId::save_estimator_components, RunnerOptionValueType::bool_value, false},
        {"refinement_history", RunnerOptionId::save_refinement_history, RunnerOptionValueType::bool_value, false},
        {"save_refinement_history", RunnerOptionId::save_refinement_history, RunnerOptionValueType::bool_value, false},
        {"mesh_statistics", RunnerOptionId::save_mesh_statistics, RunnerOptionValueType::bool_value, false},
        {"save_mesh_statistics", RunnerOptionId::save_mesh_statistics, RunnerOptionValueType::bool_value, false},
        {"save_snapshots", RunnerOptionId::save_iteration_snapshots, RunnerOptionValueType::bool_value, false},
        {"snapshots", RunnerOptionId::save_iteration_snapshots, RunnerOptionValueType::bool_value, false},
        {"save_iteration_snapshots", RunnerOptionId::save_iteration_snapshots, RunnerOptionValueType::bool_value, false},
        {"save_snapshot_dofs", RunnerOptionId::save_snapshot_dofs, RunnerOptionValueType::bool_value, false},
        {"snapshot_dofs", RunnerOptionId::save_snapshot_dofs, RunnerOptionValueType::bool_value, false},
        {"enable_timing_breakdown", RunnerOptionId::enable_timing_breakdown, RunnerOptionValueType::bool_value, false},
        {"timing_breakdown", RunnerOptionId::enable_timing_breakdown, RunnerOptionValueType::bool_value, false},
        {"timing_history_filename", RunnerOptionId::timing_history_filename, RunnerOptionValueType::string_value, false},
        {"timing_detail_level", RunnerOptionId::timing_detail_level, RunnerOptionValueType::string_value, false},
        {"list_examples", RunnerOptionId::list_examples, RunnerOptionValueType::bool_value, false},
        {"help", RunnerOptionId::show_help, RunnerOptionValueType::bool_value, false},
        {"show_help", RunnerOptionId::show_help, RunnerOptionValueType::bool_value, false}
    });

    [[nodiscard]] inline const CliOptionSpec* find_cli_option_spec(
        std::string_view flag)
    {
        const auto it =
            std::find_if(
                cli_option_specs.begin(),
                cli_option_specs.end(),
                [flag](const CliOptionSpec& spec)
                {
                    return spec.flag == flag;
                });

        return it == cli_option_specs.end() ? nullptr : &*it;
    }

    [[nodiscard]] inline const ConfigOptionSpec* find_config_option_spec(
        std::string_view key)
    {
        const auto it =
            std::find_if(
                config_option_specs.begin(),
                config_option_specs.end(),
                [key](const ConfigOptionSpec& spec)
                {
                    return spec.key == key;
                });

        return it == config_option_specs.end() ? nullptr : &*it;
    }
}
